services:
  - type: web
    name: restaurant-backend
    env: node
    plan: free
    buildCommand: cd restaurant-backend && npm install && npm run build
    startCommand: cd restaurant-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production